### ISSUE TITLE
The video resource at the bottom of the lab doesn't match the lab anymore

### ISSUE THREAD

**Issue by miriamAtFlatiron** [learn-co-students/sinatra-nested-forms-v-000#1272]
The video uses a database, so a student thought it was just a code-along, and did that, and ended up with a sqlite3 connection in his environment.rb file, etc, etc. The lab is marked with "You DO NOT NEED A DATABASE". Maybe add a note on the link to the video saying that the video isn't the same at the lab?

**Comment by lizbur10** [comment]
Thanks @miriamAtFlatiron ! The link has been removed
